# web/Dockerfile.dev
FROM node:20-alpine

WORKDIR /app

COPY package.json ./
RUN npm install --no-audit --registry=https://registry.npmjs.org/

COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]
